/*

This Java source file was generated by the Gradle 'init' task.*/
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;

import java.io.FileNotFoundException;
import java.io.FileReader;


public class Compiler {
    public static void main(String[] args) throws FileNotFoundException {

        Lexer lexer = new Lexer(new FileReader(args[1]));
        while (true) {
            Symbol symbol = lexer.getNextSymbol();
            if(symbol==null) break;
            System.out.println(symbol);
        }
    }
}